"""SAR vessel detector training scaffold (Roadmap Task 2.1).

Task 2.1 is to fine-tune a lightweight vision model, optimise it with NVIDIA
TensorRT, and serve it (as a NIM) behind the `detect_vessels(..., backend=...)`
seam already left in `vision.py`. That step needs a GPU, curated labels and a
training framework — none of which live in this repo, and none of which this
file fabricates.

What IS real and runnable here (no GPU, no torch):
  - validate a curated dataset (from curation.py) is training-ready,
  - split it into train/val deterministically,
  - emit the Ultralytics `data.yaml` the trainer consumes,
  - print the exact train + TensorRT-export commands.

What is DEFERRED to real hardware (a `ponytail:` ceiling, not a stub that lies):
  - the fine-tune itself and the TensorRT engine build. `--train` runs them only
    if ultralytics is installed and the data is present; otherwise it fails with
    an instruction. It never prints an accuracy it did not measure.

    python src/train_detector.py                          # self-check
    python src/train_detector.py --data datasets/sar_vessels --dry-run
    python src/train_detector.py --data datasets/sar_vessels --train   # needs GPU
"""

import argparse
import json
import random
import sys
from pathlib import Path

CLASS_NAMES = ["vessel"]


def _validate_labels(label_paths: list) -> list:
    """Return a list of problems; empty means every label file is YOLO-valid."""
    problems = []
    for path in label_paths:
        for lineno, line in enumerate(path.read_text().splitlines(), start=1):
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 5:
                problems.append(f"{path}:{lineno}: expected 5 fields, got {len(parts)}")
                continue
            try:
                cls = int(parts[0])
                vals = [float(x) for x in parts[1:]]
            except ValueError:
                problems.append(f"{path}:{lineno}: non-numeric field")
                continue
            if not 0 <= cls < len(CLASS_NAMES):
                problems.append(f"{path}:{lineno}: class id {cls} out of range")
            if not all(0.0 <= v <= 1.0 for v in vals):
                problems.append(f"{path}:{lineno}: coordinate outside [0,1]")
            if vals[2] <= 0 or vals[3] <= 0:
                problems.append(f"{path}:{lineno}: non-positive box size")
    return problems


def prepare(data_dir: Path, val_fraction: float = 0.2, seed: int = 0) -> dict:
    """Validate + split a curated dataset; write data.yaml, train.txt, val.txt."""
    data_dir = Path(data_dir)
    img_dir, lbl_dir = data_dir / "images", data_dir / "labels"
    if not img_dir.is_dir() or not lbl_dir.is_dir():
        raise FileNotFoundError(
            f"{data_dir} has no images/ and labels/. Run curation first:\n"
            f"  python src/curation.py --synthetic 8 --out {data_dir}")

    images = sorted(img_dir.glob("*.npy"))
    if not images:
        raise FileNotFoundError(f"no .npy images in {img_dir}")

    labelled, unlabelled = [], []
    for img in images:
        lbl = lbl_dir / f"{img.stem}.txt"
        (labelled if lbl.exists() else unlabelled).append(img)

    problems = _validate_labels([lbl_dir / f"{i.stem}.txt" for i in labelled])
    if problems:
        raise ValueError("dataset is not training-ready:\n  "
                         + "\n  ".join(problems[:20]))

    manifest_path = data_dir / "manifest.json"
    review_pending = 0
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text())
        review_pending = sum(1 for e in manifest.get("entries", [])
                             if e.get("review_status") == "pending")

    rng = random.Random(seed)
    shuffled = labelled[:]
    rng.shuffle(shuffled)
    n_val = max(1, int(len(shuffled) * val_fraction)) if len(shuffled) > 1 else 0
    val, train = shuffled[:n_val], shuffled[n_val:]

    (data_dir / "train.txt").write_text(
        "\n".join(str(p.resolve()) for p in train) + "\n")
    (data_dir / "val.txt").write_text(
        "\n".join(str(p.resolve()) for p in val) + "\n")

    data_yaml = data_dir / "data.yaml"
    data_yaml.write_text(
        f"# Ultralytics dataset config, generated by train_detector.py\n"
        f"path: {data_dir.resolve()}\n"
        f"train: train.txt\n"
        f"val: val.txt\n"
        f"nc: {len(CLASS_NAMES)}\n"
        f"names: {CLASS_NAMES}\n")

    return {
        "data_yaml": data_yaml,
        "train": len(train), "val": len(val),
        "unlabelled": len(unlabelled),
        "review_pending": review_pending,
    }


def _print_readiness(info: dict, data_dir: Path) -> None:
    print(f"\n  Dataset training-readiness ({data_dir}):")
    print(f"    train chips        {info['train']}")
    print(f"    val chips          {info['val']}")
    print(f"    unlabelled chips   {info['unlabelled']} (excluded)")
    print(f"    data.yaml          {info['data_yaml']}")
    if info["review_pending"]:
        print(f"\n  WARNING: {info['review_pending']} chip(s) still have "
              f"review_status='pending'. These carry CFAR auto-candidate labels "
              f"a human has not verified; training on them teaches the detector "
              f"the CFAR baseline's own false positives.")


def _print_commands(info: dict) -> None:
    print("\n  To fine-tune and export (needs a GPU + `pip install -r "
          "requirements-train.txt`):")
    print(f"    yolo detect train data={info['data_yaml']} model=yolo11n.pt "
          f"imgsz=256 epochs=100")
    print("    yolo export model=runs/detect/train/weights/best.pt format=engine "
          "half=True   # TensorRT")
    print("  Then wire the .engine into vision.detect_vessels(backend='trt'); its "
          "detections use the same contract as the CFAR path.")


def train(info: dict) -> int:
    """Real fine-tune + TensorRT export. Deferred to hardware; never faked.

    ponytail: this is the one seam that cannot run here — no GPU, no weights, no
    training framework. Upgrade path: install requirements-train.txt on a GPU
    host and this hands off to Ultralytics. It intentionally does no work and
    reports no metrics unless that stack is actually present.
    """
    try:
        from ultralytics import YOLO
    except ImportError:
        print("\n[train] ultralytics is not installed. This step needs a GPU and:"
              "\n  pip install -r requirements-train.txt"
              "\nThe data is prepared; run the commands above on a GPU host, or "
              "re-run with --train once the framework is installed.",
              file=sys.stderr)
        return 1
    # A GPU host with the framework present: hand off to the real trainer. Left
    # as the single integration point, deliberately not exercised in this repo.
    model = YOLO("yolo11n.pt")
    model.train(data=str(info["data_yaml"]), imgsz=256, epochs=100)
    model.export(format="engine", half=True)  # TensorRT engine
    print("[train] fine-tune + TensorRT export complete; wire the .engine into "
          "vision.detect_vessels(backend='trt').")
    return 0


def _selfcheck() -> None:
    """Runnable check: curate a tiny synthetic set, then prove it is train-ready.

    Exercises the whole data-prep path (validate + split + data.yaml) with no
    torch and no GPU — the part of Task 2.1 that can honestly run here.
    """
    import tempfile
    import curation

    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "ds"
        curation.build_dataset(curation._synthetic_chips(6), out,
                               curation._SYNTH_GEO)
        info = prepare(out, val_fraction=0.34, seed=1)
        assert info["train"] >= 1 and info["val"] >= 1, info
        assert info["data_yaml"].exists()
        # The split must be a partition: no chip in both, none lost.
        train_lines = (out / "train.txt").read_text().split()
        val_lines = (out / "val.txt").read_text().split()
        assert set(train_lines).isdisjoint(val_lines)
        assert len(train_lines) + len(val_lines) == 6
        # A corrupt label must be caught, not silently trained on.
        bad = out / "labels" / "synth_000.txt"
        bad.write_text("0 1.5 0.5 0.2 0.2\n")  # x_center out of [0,1]
        try:
            prepare(out)
            raise AssertionError("expected an out-of-range label to be rejected")
        except ValueError:
            pass
    print("train scaffold self-check passed: curate -> validate -> split -> "
          "data.yaml, and a bad label is rejected")


def main() -> int:
    parser = argparse.ArgumentParser(description="SAR detector training scaffold")
    parser.add_argument("--data", type=Path, help="curated dataset directory")
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true",
                        help="prepare + validate + print commands; do not train")
    parser.add_argument("--train", action="store_true",
                        help="run the real fine-tune (needs GPU + framework)")
    args = parser.parse_args()

    if not args.data:
        _selfcheck()
        return 0

    info = prepare(args.data, args.val_fraction, args.seed)
    _print_readiness(info, args.data)
    _print_commands(info)

    if args.train:
        return train(info)
    return 0


if __name__ == "__main__":
    sys.exit(main())
